{% set name = "sphinx-markdown-builder" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx-markdown-builder-{{ version }}.tar.gz
  sha256: febd8e03e20e357e624c52efdc7ef9d5ab70d58549784158033c9657d040f44e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - sphinx >=5.1.0
    - tabulate
    - docutils

test:
  imports:
    - sphinx_markdown_builder
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A Sphinx extension to add markdown generation support.
  home: https://github.com/liran-funaro/sphinx-markdown-builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raispbizerra
    - igortg
    - LucasRochaAbraao
