{% set name = "sphinx-markdown-builder" %}
{% set version = "0.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 9623c8d5963e18b3733ec8335a48b58c3e556a96529b73e4c65113cabd8e8591

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0.0
    - wheel
    - poetry-core
    - pip
  run:
    - python >=3.7
    - sphinx >=5.1.0
    - tabulate
    - docutils

test:
  imports:
    - sphinx_markdown_builder
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Sphinx extension to add markdown generation support.
  home: https://github.com/liran-funaro/sphinx-markdown-builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raispbizerra
    - igortg
    - LucasRochaAbraao
