{% set name = "sphinx-markdown-builder" %}
{% set version = "0.6.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6141b566bf18dd1cd515a0a90efd91c6c4d10fc638554fab2fd19cba66543dd7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0.0
    - wheel
    - poetry-core
    - pip
  run:
    - python >=3.7
    - sphinx >=5.1.0
    - tabulate
    - docutils

test:
  imports:
    - sphinx_markdown_builder
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A Sphinx extension to add markdown generation support.
  home: https://github.com/liran-funaro/sphinx-markdown-builder
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raispbizerra
    - igortg
    - LucasRochaAbraao
